### PATCH actualizar solo nombre y teléfono
PATCH http://localhost:8080/users/0e435e72-df74-4632-96ec-d9b3a0456afe
Content-Type: application/json

{
  "name": "Usuario Actualizado",
  "password": "mipassword123"
}
