
### Antes de ejecutar este test, asegúrate de tener el servidor corriendo en http://localhost:8080
### Actualizar el usuario con tax_id "BBBS990202YYY" y password "mipassword123" (hash "4e0IU0JJo6M8ZvnrzqhZNg==") para este test.
### LOGIN correcto
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "tax_id": "BBBS990202YYY",
  "password": "mipassword123"
}

###